# Generated by Django 4.1.4 on 2023-04-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factor',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_management.customer'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_management.deliverer'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant_management.order'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
