# Generated by Django 4.1.4 on 2023-04-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0002_factor_complete_alter_factor_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='total_price',
        ),
    ]
